### ISSUE TITLE
请问这个现在能使用吗

### ISSUE THREAD

**Issue by qytayh** [amebyte/ffmpeg-download#3]
我在macos环境
node v16
<img width="646" alt="image" src="https://user-images.githubusercontent.com/39668309/181462530-3afb884e-e609-49c7-9c4a-2fb0527086b6.png">
 我这边的提示是访问被拒绝
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/39668309/181462822-21571dc7-6a48-44d7-91c2-f4fdd39c5598.png">
请问是我配置有问题吗

**Comment by amebyte** [comment]
应该可以吧，应该是你配置有问题，KKB网站能上，应该就还可以的

**Comment by qytayh** [comment]
> 

已经在下了  工具很好用 妙得很  万分感谢
